#pragma once

#define SERVER_MAX_CONNECTIONS	8050
#define SERVER_MAX_INCOMING_CONNECTIONS	8000
#define CLIENT_MAX_CONNECTIONS	1
#define CLIENT_CONNECTION_ATTEMPT_COUNT	10
#define CLIENT_TIME_BTW_SEND_CONNECTION_ATTEMPT_COUNT	1000
